/**
 * THE CHEAT MENU (boss ask 2026-07-16, testing tool). The load-bearing claims:
 *  - cheats are COMMANDS: they enter the log, so a cheated world REPLAYS byte-for-byte,
 *    cheats and all (the one law that makes a cheat safe to keep in the tree);
 *  - cheat_give adds exactly what it says; grain honors the granaries' cap like a
 *    harvest would (a cheat tests the game, it does not invent a bigger barn);
 *  - cheat_spawn_person adds a working adult villager who joins the dawn pass;
 *  - malformed cheats are chronicled, not crashed;
 *  - a world with no cheats is unchanged (pure vocabulary — the baseline instrument
 *    guards it: the SIM 37 canon regenerated byte-identically around this commit).
 */
import { describe, expect, it } from 'vitest';
import { hashState, makeSave, replay } from '../src/sim/save';
import { flatSite } from '../src/sim/site';
import { worldStep } from '../src/sim/step';
import { createWorld } from '../src/sim/world';
import { FOUNDING_STORAGE, SEED_GRAIN, SEED_TIMBER, type Command } from '../src/sim/types';

const site = flatSite('flat', 4000);

function run(commands: Command[], ticks: number) {
  const byTick = new Map<number, Command[]>();
  for (const c of commands) (byTick.get(c.tick) ?? byTick.set(c.tick, []).get(c.tick)!).push(c);
  const world = createWorld('cheat-seed', site.id);
  for (let t = 0; t < ticks; t++) worldStep(world, site, byTick.get(world.tick) ?? []);
  return world;
}

describe('the cheat menu (testing tool)', () => {
  it('cheat_give adds exactly what it says — and grain honors the granary cap', () => {
    const w = run([{ kind: 'cheat_give', tick: 0, stone: 100, timber: 50, grain: 1000 }], 1);
    expect(w.stockpile).toBe(100);
    expect(w.timber).toBe(SEED_TIMBER + 50);
    expect(w.grain).toBe(FOUNDING_STORAGE); // capped: no granaries, so the bare larder's cap
    expect(SEED_GRAIN).toBeLessThanOrEqual(FOUNDING_STORAGE); // the cap premise
    expect(w.events.some((e) => e.kind === 'cheat_given')).toBe(true); // on the record
  });

  it('cheat_spawn_person adds a working adult villager', () => {
    const w = run([{ kind: 'cheat_spawn_person', tick: 0, at: { x: 100, y: 100 } }], 1);
    expect(w.people).toHaveLength(14); // the thirteen founders + the decree
    const soul = w.people[13]!;
    expect(soul.trade).toBe('villager');
    expect(w.events.some((e) => e.kind === 'person_arrived' && e.personId === soul.id)).toBe(true);
  });

  it('a cheated world replays byte-for-byte — the log carries the cheat', () => {
    const cmds: Command[] = [
      { kind: 'cheat_give', tick: 0, stone: 100 },
      { kind: 'cheat_spawn_person', tick: 2, at: { x: 100, y: 100 } },
      { kind: 'plan_wall', tick: 3, points: [{ x: 0, y: 0 }, { x: 30, y: 0 }], height: 1 },
    ];
    const live = run(cmds, 20);
    expect(live.stones.length).toBeGreaterThan(0); // the cheated stone got laid
    const replayed = replay(makeSave(live, cmds), site, 20);
    expect(hashState(replayed)).toBe(hashState(live));
  });

  it('malformed cheats are chronicled, not crashed', () => {
    const w = run(
      [
        { kind: 'cheat_give', tick: 0 }, // gives nothing
        { kind: 'cheat_give', tick: 0, stone: -5 }, // negative
        { kind: 'cheat_spawn_person', tick: 0, at: { x: NaN, y: 0 } }, // bad point
      ],
      1,
    );
    expect(w.events.filter((e) => e.kind === 'command_rejected')).toHaveLength(3);
    expect(w.stockpile).toBe(0);
    expect(w.people).toHaveLength(13);
  });
});
